# Generated by Django 4.2.6 on 2023-10-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
